# Generated by Django 3.1.5 on 2021-02-12 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
